import Head from "next/head";
import clsx from "clsx";
import styles from "./Onboarding.module.css";
import { Button, LinkButton } from "@/components/Button";
import Main from "@/components/MainContainer";

export default function Onboarding() {
  return (
    <>
      <Head>
        <title>Welcome to Ledger Fresh</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={clsx(styles.bg)}></div>
      <div className={clsx(styles.bg2)}></div>
      <div className="page">
        <Main variant="centered" className={styles.main}>
          <h1>Welcome to Ledger Fresh</h1>
        </Main>
        <div className={styles.buttonRow}>
          <LinkButton
            href="/create"
            variant="primary"
            className={styles.onboarding_button}
          >
            Create a new wallet
          </LinkButton>
          <LinkButton href="/" variant="subtle">
            I already have a wallet
          </LinkButton>
        </div>
      </div>
    </>
  );
}
