import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Main from "@/components/MainContainer";
import { Header } from "@/components/Header";
import { LinkButton } from "@/components/Button";

export default function Home() {
  return (
    <>
      <Head>
        <title>
          Ledger Fresh -- Abstract your account using this web wallet
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Main variant="centered">
        <div className={styles.description}>
          <h1>Ledger Fresh</h1>
        </div>
        <LinkButton href={"/onboarding"}>Onboarding</LinkButton>
      </Main>
    </>
  );
}
