import Head from "next/head";
import clsx from "clsx";
import styles from "./Emboarding.module.css";
import { Button, LinkButton } from "../../components/Button";

export default function Emboarding() {
  return (
    <>
      <Head>
        <title>Welcome to Ledger Fresh</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={clsx(styles.bg)}></div>
      <div className={clsx(styles.bg2)}></div>
      <div className={clsx(styles.page)}>
        <main className={styles.main}>
          <h1>Welcome to Ledger Fresh</h1>
        </main>
        <div className={styles.buttonRow}>
          <LinkButton
            href="/create"
            variant="primary"
            className={styles.emboarding_button}
          >
            Create a new wallet
          </LinkButton>
          <LinkButton href="/import" variant="subtle">
            I already have a wallet
          </LinkButton>
        </div>
      </div>
    </>
  );
}
